
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COMMA IDENTIFIER LBRACE LPARA RBRACE RET RPARA SEMICOLON SYMBOL TYPEdeclaration : TYPE IDENTIFIER LBRACE para RBRACE LPARA inside RPARA inside : TYPE IDENTIFIER ASSIGN IDENTIFIER SEMICOLONinside : RET IDENTIFIER SEMICOLONpara : TYPE IDENTIFIER\n              | TYPE IDENTIFIER COMMA paraempty :'
    
_lr_action_items = {'TYPE':([0,4,9,10,],[2,5,5,12,]),'$end':([1,16,],[0,-1,]),'IDENTIFIER':([2,5,12,14,18,],[3,7,15,17,20,]),'LBRACE':([3,],[4,]),'RBRACE':([6,7,11,],[8,-4,-5,]),'COMMA':([7,],[9,]),'LPARA':([8,],[10,]),'RET':([10,],[14,]),'RPARA':([13,19,21,],[16,-3,-2,]),'ASSIGN':([15,],[18,]),'SEMICOLON':([17,20,],[19,21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),'para':([4,9,],[6,11,]),'inside':([10,],[13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> TYPE IDENTIFIER LBRACE para RBRACE LPARA inside RPARA','declaration',8,'p_declaration','function_def.py',64),
  ('inside -> TYPE IDENTIFIER ASSIGN IDENTIFIER SEMICOLON','inside',5,'p_inside_assign','function_def.py',69),
  ('inside -> RET IDENTIFIER SEMICOLON','inside',3,'p_inside_ret','function_def.py',73),
  ('para -> TYPE IDENTIFIER','para',2,'p_para','function_def.py',81),
  ('para -> TYPE IDENTIFIER COMMA para','para',4,'p_para','function_def.py',82),
  ('empty -> <empty>','empty',0,'p_empty','function_def.py',87),
]
